-- 1. What is the total amount each customer spent at the restaurant?
SELECT customer_id, SUM(price) AS total_spent
FROM sales
JOIN menu ON sales.product_id = menu.product_id
GROUP BY customer_id;

-- 2. How many unique items has each customer purchased from the menu?
SELECT customer_id, COUNT(DISTINCT product_id) AS unique_items_purchased
FROM sales
GROUP BY customer_id;

-- 3. What is the average amount spent by each customer per visit?
SELECT customer_id, AVG(price) AS average_spent_per_visit
FROM sales
JOIN menu ON sales.product_id = menu.product_id
GROUP BY customer_id;

-- 4. Which menu item is the most popular across all customers?
SELECT product_name, COUNT(*) AS times_purchased
FROM sales
JOIN menu ON sales.product_id = menu.product_id
GROUP BY product_name
ORDER BY times_purchased DESC
LIMIT 1;

-- 5. What was the most expensive item purchased by each customer?
SELECT customer_id, MAX(price) AS most_expensive_item
FROM sales
JOIN menu ON sales.product_id = menu.product_id
GROUP BY customer_id;

-- 6. Which day of the week is the most popular for customers to visit?
SELECT DAYNAME(sale_date) AS day_of_week, COUNT(*) AS visits
FROM sales
GROUP BY day_of_week
ORDER BY visits DESC
LIMIT 1;

-- 7. What is the total number of visits made by each customer?
SELECT customer_id, COUNT(*) AS total_visits
FROM sales
GROUP BY customer_id;

-- 8. Which customer has the highest total spend at the restaurant?
SELECT customer_id, SUM(price) AS total_spent
FROM sales
JOIN menu ON sales.product_id = menu.product_id
GROUP BY customer_id
ORDER BY total_spent DESC
LIMIT 1;

-- 9. How many customers purchased at least 3 different items on the same day?
SELECT customer_id, sale_date
FROM sales
GROUP BY customer_id, sale_date
HAVING COUNT(DISTINCT product_id) >= 3;

-- 10. What is the total revenue generated by each menu item?
SELECT product_name, SUM(price) AS total_revenue
FROM sales
JOIN menu ON sales.product_id = menu.product_id
GROUP BY product_name
ORDER BY total_revenue DESC;

-- 11. How many customers purchased the same item more than once?
SELECT customer_id, product_id, COUNT(*) AS times_purchased
FROM sales
GROUP BY customer_id, product_id
HAVING times_purchased > 1;


-- 12. Which customer spent the most on a single visit?
SELECT customer_id, sale_date, SUM(price) AS total_spent
FROM sales
JOIN menu ON sales.product_id = menu.product_id
GROUP BY customer_id, sale_date
ORDER BY total_spent DESC
LIMIT 1;


-- 13. What is the total amount spent on each menu item by all customers?
SELECT product_name, SUM(price) AS total_spent
FROM sales
JOIN menu ON sales.product_id = menu.product_id
GROUP BY product_name
ORDER BY total_spent DESC;

-- 14. How many customers have only made one purchase at the restaurant?
SELECT customer_id, COUNT(*) AS total_purchases
FROM sales
GROUP BY customer_id
HAVING total_purchases = 1;


-- 15. Find the customers who spent more than the average spend per customer.
SELECT customer_id, SUM(price) AS total_spent
FROM sales
JOIN menu ON sales.product_id = menu.product_id
GROUP BY customer_id
HAVING SUM(price) > (SELECT AVG(total_spent) FROM (
    SELECT customer_id, SUM(price) AS total_spent
    FROM sales
    JOIN menu ON sales.product_id = menu.product_id
    GROUP BY customer_id
) AS avg_spent);

-- 16. Find the top 3 customers who made the most purchases in the last month of data available.
SELECT customer_id, COUNT(*) AS purchase_count
FROM sales
WHERE sale_date BETWEEN 
      (SELECT DATE_SUB(MAX(sale_date), INTERVAL 1 MONTH) FROM sales) 
      AND (SELECT MAX(sale_date) FROM sales)
GROUP BY customer_id
ORDER BY purchase_count DESC
LIMIT 3;



-- 17. Find the average spend per visit for each customer, but only include visits where they spent more than the average spend for all visits.
SELECT customer_id, AVG(total_spent_per_visit) AS avg_spent_per_visit
FROM (
    SELECT customer_id, sale_date, SUM(price) AS total_spent_per_visit
    FROM sales
    JOIN menu ON sales.product_id = menu.product_id
    GROUP BY customer_id, sale_date
    HAVING total_spent_per_visit > (
        SELECT AVG(total_spent) FROM (
            SELECT SUM(price) AS total_spent
            FROM sales
            JOIN menu ON sales.product_id = menu.product_id
            GROUP BY customer_id, sale_date
        ) AS overall_avg
    )
) AS high_spending_visits
GROUP BY customer_id;

-- 18.List the menu items that were purchased by the customer who has spent the most in total.
SELECT DISTINCT menu.product_name
FROM sales
JOIN menu ON sales.product_id = menu.product_id
WHERE sales.customer_id = (
    SELECT customer_id
    FROM (
        SELECT customer_id, SUM(price) AS total_spent
        FROM sales
        JOIN menu ON sales.product_id = menu.product_id
        GROUP BY customer_id
        ORDER BY total_spent DESC
        LIMIT 1
    ) AS top_spender
);

-- 19. Find the total amount spent on a specific menu item (e.g., "Dosa").
SELECT SUM(price) AS total_spent
FROM sales
JOIN menu ON sales.product_id = menu.product_id
WHERE menu.product_name = 'Dosa';

-- 20 Get the list of customers who made a purchase in a specific month (e.g., January 2021
SELECT  DISTINCT customer_id
FROM sales
WHERE sale_date BETWEEN '2021-04-01' AND '2021-04-30';


